# Generated by Django 2.1.4 on 2019-01-03 10:23

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('name', models.CharField(max_length=200)),
                ('cuisine', models.CharField(choices=[('Burgerim', 'Burgerim'), ('Sushi', 'Sushi'), ('Pizza', 'Pizza'), ('Fish', 'Fish'), ('Other', 'Other')], default='Other', max_length=20)),
                ('ten_bis', models.BooleanField(default=False)),
                ('address', models.CharField(max_length=200)),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '*'), (2, '**'), (3, '***')])),
                ('maximum_delivery_time', models.IntegerField(default=60, validators=[django.core.validators.MaxValueValidator(300), django.core.validators.MinValueValidator(1)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
