# Generated by Django 2.1.4 on 2019-01-04 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('we_eat', '0002_choice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='votes',
        ),
        migrations.AddField(
            model_name='choice',
            name='vote',
            field=models.IntegerField(default=1),
        ),
    ]
