# Generated by Django 2.1.4 on 2019-01-04 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('we_eat', '0003_auto_20190104_2134'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='vote',
            new_name='votes',
        ),
    ]
